site_name: Hardening Ubuntu Docs
site_description: Documentação didática do projeto de hardening do Ubuntu.
repo_url: https://github.com/maurocapuanopy-source/hardening
repo_name: maurocapuanopy-source/hardening
site_url: https://maurocapuanopy-source.github.io/hardening/

theme:
  name: material
  language: pt-BR
  logo: logo/horizontal.png
  favicon: logo/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo Claro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo Escuro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Início: index.md
  - Apresentação: apresentacao.md
  - 🛠️ Guia de Início:
      - Quick Start: guias/quick-start.md
      - Preparação de S.O: guias/preparacao.md
      - Execução do Script: guias/execucao.md
  - 🚀 Automação:
      - Ansible: guia-ansible.md
      - Docker: guia-docker.md
  - 🛡️ Proteções em Detalhe:
      - Kernel & Sistemas de Arquivos: protecoes/kernel.md
      - Rede & Firewall: protecoes/rede-firewall.md
      - Acesso & Identidade: protecoes/acesso-identidade.md
      - Auditoria & Monitoramento: protecoes/auditoria.md
  - ⚖️ Referência:
      - Manual Técnico: manual.md
      - Testes de Conformidade: guias/testes.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.grid
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
