site_name: Hardening Ubuntu Docs
site_description: Documentação didática do projeto de hardening do Ubuntu.
repo_url: https://github.com/maurocapuanopy-source/hardening
repo_name: maurocapuanopy-source/hardening
site_url: https://maurocapuanopy-source.github.io/hardening/

theme:
  name: material
  language: pt-BR
  logo: logo/horizontal.png
  favicon: logo/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo Claro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo Escuro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

nav:
  - Início: index.md
  - Automação:
      - Ansible: guia-ansible.md
      - Docker: guia-docker.md
  - Referência Técnica: manual.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
